import { IconType } from "react-icons";
import { BiCar, BiMapPin, BiTaxi } from "react-icons/bi";
import { FaPlane } from "react-icons/fa";
import { LuBedDouble } from "react-icons/lu";
import { SlHandbag } from "react-icons/sl";

//
import england from "../assets/england.jpeg";
import birmingham from "../assets/birmingham.jpeg";
import london from "../assets/london.jpeg";
import paris from "../assets/paris.jpeg";
import liverpool from "../assets/liverpool.jpeg";

export const navigation: {
  id: number;
  title: string;
  path: string;
  icon: IconType;
}[] = [
  {
    id: 1,
    title: "Stays",
    path: "/",
    icon: LuBedDouble,
  },
  {
    id: 2,
    title: "Flights",
    path: "/hotels",
    icon: FaPlane,
  },
  {
    id: 3,
    title: "Flight + Hotels",
    path: "/about",
    icon: SlHandbag,
  },
  {
    id: 4,
    title: "Car rentals",
    path: "/contact",
    icon: BiCar,
  },
  {
    id: 5,
    title: "Attractions",
    path: "/contact",
    icon: BiMapPin,
  },
  {
    id: 6,
    title: "Airport taxis",
    path: "/contact",
    icon: BiTaxi,
  },
];

export const trendingDestination = [
  {
    location: "England",
    image: england,
  },
  {
    location: "Birmingham",
    image: birmingham,
  },
  {
    location: "London",
    image: london,
  },
  {
    location: "Paris",
    image: paris,
  },
  {
    location: "Liverpool",
    image: liverpool,
  },
];
export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, North",
  "Korea, South",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];
export const faclities = [
  "Room service",
  "Bar",
  "24-hour front desk",
  "Sauna",
  "Fitness center",
  "Garden",
  "Terrace",
  "Non-smoking rooms",
  "Airport shuttle",
  "Family rooms",
  "Spa",
  "Hot tub/Jacuzzi",
  "Free WiFi",
  "Air conditioning",
  "Water park",
  "Electric vehicle charging station",
  "Swimming pool",
  "Beach",
];
